### ISSUE TITLE
/facade/cart

### ISSUE THREAD

**Issue by aquadancer** [JackieDo/Laravel-Cart#38]
why did you write a facade on the basket, if you didn’t write it down phpDoc,
For exaple check that class \Illuminate\Support\Facades\Cache
it turns out that autocomplete will work and everything will be cool, otherwise I don’t even understand where these methods come from, I had to go to your service provider and see what your facade refers to

**Comment by JackieDo** [comment]
You are very correct, this is my omission. I wrote this package for our developer community to use but forgot about this. I accept my shortcomings.

I will fill in these omissions in the source code. But in the present time, I am too busy to do it right now. In the meantime, please use the instructions page [here](https://jackiedo.github.io/Laravel-Cart/#/).
